FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Set NODE_ENV to development
ENV NODE_ENV=development

# Install dependencies
RUN npm install

# Copy source code
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"] 